language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
# command to install dependencies
install:
   - sudo apt-get -y update
   - sudo apt-get -y install build-essential
   - curl ftp://ftp.gnu.org/gnu/gsl/gsl-2.3.tar.gz -o gsl-2.3.tar.gz
   - tar -xvzf gsl-2.3.tar.gz
   - cd gsl-2.3/
   - ./configure
   - make
   - sudo make install
   - cd
   - pip install -r requirements.txt
   - python setup.py build_ext
   - python setup.py install
script: python topicmodel_tests/testsuite.py
branches:
  only:
    - master
    - with_gsl
    